# Challenge 1

In this challenge you will be working on **Pokemon**. You will answer a series of questions in order to practice dataframe calculation, aggregation, and transformation.

![Pokemon](../images/pokemon.jpg)

Follow the instructions below and enter your code.

#### Import all required libraries.

In [4]:
import pandas as pd

#### Import data set.

Read the dataset `pokemon.csv` into a dataframe called `pokemon`.

*Data set attributed to [Alberto Barradas](https://www.kaggle.com/abcsds/pokemon/)*

In [5]:
pokemon = pd.read_csv(r"C:\Users\Usuario\Desktop\Week 3\lab-dataframe-calculations\your-code\Pokemon.csv")
pokemon

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

#### Print first 10 rows of `pokemon`.

In [6]:
pokemon.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False

When you look at a data set, you often wonder what each column means. Some open-source data sets provide descriptions of the data set. In many cases, data descriptions are extremely useful for data analysts to perform work efficiently and successfully.

For the `Pokemon.csv` data set, fortunately, the owner provided descriptions which you can see [here](https://www.kaggle.com/abcsds/pokemon/home). For your convenience, we are including the descriptions below. Read the descriptions and understand what each column means. This knowledge is helpful in your work with the data.

| Column | Description |
| --- | --- |
| # | ID for each pokemon |
| Name | Name of each pokemon |
| Type 1 | Each pokemon has a type, this determines weakness/resistance to attacks |
| Type 2 | Some pokemon are dual type and have 2 |
| Total | A general guide to how strong a pokemon is |
| HP | Hit points, or health, defines how much damage a pokemon can withstand before fainting |
| Attack | The base modifier for normal attacks (eg. Scratch, Punch) |
| Defense | The base damage resistance against normal attacks |
| SP Atk | Special attack, the base modifier for special attacks (e.g. fire blast, bubble beam) |
| SP Def | The base damage resistance against special attacks |
| Speed | Determines which pokemon attacks first each round |
| Generation | Number of generation |
| Legendary | True if Legendary Pokemon False if not |

#### Obtain the distinct values across `Type 1` and `Type 2`.

Exctract all the values in `Type 1` and `Type 2`. Then create an array containing the distinct values across both fields.

In [7]:
pokemon[["Type 1", "Type 2"]]

      Type 1  Type 2
0      Grass  Poison
1      Grass  Poison
2      Grass  Poison
3      Grass  Poison
4       Fire     NaN
..       ...     ...
795     Rock   Fairy
796     Rock   Fairy
797  Psychic   Ghost
798  Psychic    Dark
799     Fire   Water

[800 rows x 2 columns]

In [8]:
array_1= pokemon["Type 1"].unique()
array_1

array(['Grass', 'Fire', 'Water', 'Bug', 'Normal', 'Poison', 'Electric',
       'Ground', 'Fairy', 'Fighting', 'Psychic', 'Rock', 'Ghost', 'Ice',
       'Dragon', 'Dark', 'Steel', 'Flying'], dtype=object)

In [9]:
array_2= pokemon["Type 2"].unique()
array_2

array(['Poison', nan, 'Flying', 'Dragon', 'Ground', 'Fairy', 'Grass',
       'Fighting', 'Psychic', 'Steel', 'Ice', 'Rock', 'Dark', 'Water',
       'Electric', 'Fire', 'Ghost', 'Bug', 'Normal'], dtype=object)

In [10]:
pokemon[["Type 1", "Type 2"]].value_counts()

Type 1    Type 2
Normal    Flying    24
Grass     Poison    15
Bug       Flying    14
          Poison    12
Water     Ground    10
                    ..
Electric  Ice        1
          Grass      1
          Fire       1
          Fairy      1
Water     Steel      1
Length: 136, dtype: int64

#### Cleanup `Name` that contain "Mega".

If you have checked out the pokemon names carefully enough, you should have found there are junk texts in the pokemon names which contain "Mega". We want to clean up the pokemon names. For instance, "VenusaurMega Venusaur" should be "Mega Venusaur", and "CharizardMega Charizard X" should be "Mega Charizard X".

In [11]:
## print(set(pokemon["Mega"]))


# test transformed data
pokemon.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False

In [12]:
##df['Grade'] = df['Grade'].str.replace('%', '')

#new_pokemon = pokemon ["Name"].str.replace("", " ")
#new_pokemon

pokemon["Name"].unique()

array(['Bulbasaur', 'Ivysaur', 'Venusaur', 'VenusaurMega Venusaur',
       'Charmander', 'Charmeleon', 'Charizard',
       'CharizardMega Charizard X', 'CharizardMega Charizard Y',
       'Squirtle', 'Wartortle', 'Blastoise', 'BlastoiseMega Blastoise',
       'Caterpie', 'Metapod', 'Butterfree', 'Weedle', 'Kakuna',
       'Beedrill', 'BeedrillMega Beedrill', 'Pidgey', 'Pidgeotto',
       'Pidgeot', 'PidgeotMega Pidgeot', 'Rattata', 'Raticate', 'Spearow',
       'Fearow', 'Ekans', 'Arbok', 'Pikachu', 'Raichu', 'Sandshrew',
       'Sandslash', 'Nidoranâ™€', 'Nidorina', 'Nidoqueen', 'Nidoranâ™‚',
       'Nidorino', 'Nidoking', 'Clefairy', 'Clefable', 'Vulpix',
       'Ninetales', 'Jigglypuff', 'Wigglytuff', 'Zubat', 'Golbat',
       'Oddish', 'Gloom', 'Vileplume', 'Paras', 'Parasect', 'Venonat',
       'Venomoth', 'Diglett', 'Dugtrio', 'Meowth', 'Persian', 'Psyduck',
       'Golduck', 'Mankey', 'Primeape', 'Growlithe', 'Arcanine',
       'Poliwag', 'Poliwhirl', 'Poliwrath', 'Abra', 'Kadabra', 'Alakazam',
       'AlakazamMega Alakazam', 'Machop', 'Machoke', 'Machamp',
       'Bellsprout', 'Weepinbell', 'Victreebel', 'Tentacool',
       'Tentacruel', 'Geodude', 'Graveler', 'Golem', 'Ponyta', 'Rapidash',
       'Slowpoke', 'Slowbro', 'SlowbroMega Slowbro', 'Magnemite',
       'Magneton', "Farfetch'd", 'Doduo', 'Dodrio', 'Seel', 'Dewgong',
       'Grimer', 'Muk', 'Shellder', 'Cloyster', 'Gastly', 'Haunter',
       'Gengar', 'GengarMega Gengar', 'Onix', 'Drowzee', 'Hypno',
       'Krabby', 'Kingler', 'Voltorb', 'Electrode', 'Exeggcute',
       'Exeggutor', 'Cubone', 'Marowak', 'Hitmonlee', 'Hitmonchan',
       'Lickitung', 'Koffing', 'Weezing', 'Rhyhorn', 'Rhydon', 'Chansey',
       'Tangela', 'Kangaskhan', 'KangaskhanMega Kangaskhan', 'Horsea',
       'Seadra', 'Goldeen', 'Seaking', 'Staryu', 'Starmie', 'Mr. Mime',
       'Scyther', 'Jynx', 'Electabuzz', 'Magmar', 'Pinsir',
       'PinsirMega Pinsir', 'Tauros', 'Magikarp', 'Gyarados',
       'GyaradosMega Gyarados', 'Lapras', 'Ditto', 'Eevee', 'Vaporeon',
       'Jolteon', 'Flareon', 'Porygon', 'Omanyte', 'Omastar', 'Kabuto',
       'Kabutops', 'Aerodactyl', 'AerodactylMega Aerodactyl', 'Snorlax',
       'Articuno', 'Zapdos', 'Moltres', 'Dratini', 'Dragonair',
       'Dragonite', 'Mewtwo', 'MewtwoMega Mewtwo X',
       'MewtwoMega Mewtwo Y', 'Mew', 'Chikorita', 'Bayleef', 'Meganium',
       'Cyndaquil', 'Quilava', 'Typhlosion', 'Totodile', 'Croconaw',
       'Feraligatr', 'Sentret', 'Furret', 'Hoothoot', 'Noctowl', 'Ledyba',
       'Ledian', 'Spinarak', 'Ariados', 'Crobat', 'Chinchou', 'Lanturn',
       'Pichu', 'Cleffa', 'Igglybuff', 'Togepi', 'Togetic', 'Natu',
       'Xatu', 'Mareep', 'Flaaffy', 'Ampharos', 'AmpharosMega Ampharos',
       'Bellossom', 'Marill', 'Azumarill', 'Sudowoodo', 'Politoed',
       'Hoppip', 'Skiploom', 'Jumpluff', 'Aipom', 'Sunkern', 'Sunflora',
       'Yanma', 'Wooper', 'Quagsire', 'Espeon', 'Umbreon', 'Murkrow',
       'Slowking', 'Misdreavus', 'Unown', 'Wobbuffet', 'Girafarig',
       'Pineco', 'Forretress', 'Dunsparce', 'Gligar', 'Steelix',
       'SteelixMega Steelix', 'Snubbull', 'Granbull', 'Qwilfish',
       'Scizor', 'ScizorMega Scizor', 'Shuckle', 'Heracross',
       'HeracrossMega Heracross', 'Sneasel', 'Teddiursa', 'Ursaring',
       'Slugma', 'Magcargo', 'Swinub', 'Piloswine', 'Corsola', 'Remoraid',
       'Octillery', 'Delibird', 'Mantine', 'Skarmory', 'Houndour',
       'Houndoom', 'HoundoomMega Houndoom', 'Kingdra', 'Phanpy',
       'Donphan', 'Porygon2', 'Stantler', 'Smeargle', 'Tyrogue',
       'Hitmontop', 'Smoochum', 'Elekid', 'Magby', 'Miltank', 'Blissey',
       'Raikou', 'Entei', 'Suicune', 'Larvitar', 'Pupitar', 'Tyranitar',
       'TyranitarMega Tyranitar', 'Lugia', 'Ho-oh', 'Celebi', 'Treecko',
       'Grovyle', 'Sceptile', 'SceptileMega Sceptile', 'Torchic',
       'Combusken', 'Blaziken', 'BlazikenMega Blaziken', 'Mudkip',
       'Marshtomp', 'Swampert', 'SwampertMega Swampert', 'Poochyena',
       'Mightyena', 'Zigzagoon', 'Linoone', 'Wurmple', 'Silcoon',
       'Beautifly', 'Cascoon', 'Dustox', 'Lotad', 'Lombre', 'Ludicolo',
       'Seedot', 'Nuzleaf', 'Shiftry', 'Taillow', 'Swellow', 'Wingull',
       'Pelipper', 'Ralts', 'Kirlia', 'Gardevoir',
       'GardevoirMega Gardevoir', 'Surskit', 'Masquerain', 'Shroomish',
       'Breloom', 'Slakoth', 'Vigoroth', 'Slaking', 'Nincada', 'Ninjask',
       'Shedinja', 'Whismur', 'Loudred', 'Exploud', 'Makuhita',
       'Hariyama', 'Azurill', 'Nosepass', 'Skitty', 'Delcatty', 'Sableye',
       'SableyeMega Sableye', 'Mawile', 'MawileMega Mawile', 'Aron',
       'Lairon', 'Aggron', 'AggronMega Aggron', 'Meditite', 'Medicham',
       'MedichamMega Medicham', 'Electrike', 'Manectric',
       'ManectricMega Manectric', 'Plusle', 'Minun', 'Volbeat',
       'Illumise', 'Roselia', 'Gulpin', 'Swalot', 'Carvanha', 'Sharpedo',
       'SharpedoMega Sharpedo', 'Wailmer', 'Wailord', 'Numel', 'Camerupt',
       'CameruptMega Camerupt', 'Torkoal', 'Spoink', 'Grumpig', 'Spinda',
       'Trapinch', 'Vibrava', 'Flygon', 'Cacnea', 'Cacturne', 'Swablu',
       'Altaria', 'AltariaMega Altaria', 'Zangoose', 'Seviper',
       'Lunatone', 'Solrock', 'Barboach', 'Whiscash', 'Corphish',
       'Crawdaunt', 'Baltoy', 'Claydol', 'Lileep', 'Cradily', 'Anorith',
       'Armaldo', 'Feebas', 'Milotic', 'Castform', 'Kecleon', 'Shuppet',
       'Banette', 'BanetteMega Banette', 'Duskull', 'Dusclops', 'Tropius',
       'Chimecho', 'Absol', 'AbsolMega Absol', 'Wynaut', 'Snorunt',
       'Glalie', 'GlalieMega Glalie', 'Spheal', 'Sealeo', 'Walrein',
       'Clamperl', 'Huntail', 'Gorebyss', 'Relicanth', 'Luvdisc', 'Bagon',
       'Shelgon', 'Salamence', 'SalamenceMega Salamence', 'Beldum',
       'Metang', 'Metagross', 'MetagrossMega Metagross', 'Regirock',
       'Regice', 'Registeel', 'Latias', 'LatiasMega Latias', 'Latios',
       'LatiosMega Latios', 'Kyogre', 'KyogrePrimal Kyogre', 'Groudon',
       'GroudonPrimal Groudon', 'Rayquaza', 'RayquazaMega Rayquaza',
       'Jirachi', 'DeoxysNormal Forme', 'DeoxysAttack Forme',
       'DeoxysDefense Forme', 'DeoxysSpeed Forme', 'Turtwig', 'Grotle',
       'Torterra', 'Chimchar', 'Monferno', 'Infernape', 'Piplup',
       'Prinplup', 'Empoleon', 'Starly', 'Staravia', 'Staraptor',
       'Bidoof', 'Bibarel', 'Kricketot', 'Kricketune', 'Shinx', 'Luxio',
       'Luxray', 'Budew', 'Roserade', 'Cranidos', 'Rampardos', 'Shieldon',
       'Bastiodon', 'Burmy', 'WormadamPlant Cloak', 'WormadamSandy Cloak',
       'WormadamTrash Cloak', 'Mothim', 'Combee', 'Vespiquen',
       'Pachirisu', 'Buizel', 'Floatzel', 'Cherubi', 'Cherrim', 'Shellos',
       'Gastrodon', 'Ambipom', 'Drifloon', 'Drifblim', 'Buneary',
       'Lopunny', 'LopunnyMega Lopunny', 'Mismagius', 'Honchkrow',
       'Glameow', 'Purugly', 'Chingling', 'Stunky', 'Skuntank', 'Bronzor',
       'Bronzong', 'Bonsly', 'Mime Jr.', 'Happiny', 'Chatot', 'Spiritomb',
       'Gible', 'Gabite', 'Garchomp', 'GarchompMega Garchomp', 'Munchlax',
       'Riolu', 'Lucario', 'LucarioMega Lucario', 'Hippopotas',
       'Hippowdon', 'Skorupi', 'Drapion', 'Croagunk', 'Toxicroak',
       'Carnivine', 'Finneon', 'Lumineon', 'Mantyke', 'Snover',
       'Abomasnow', 'AbomasnowMega Abomasnow', 'Weavile', 'Magnezone',
       'Lickilicky', 'Rhyperior', 'Tangrowth', 'Electivire', 'Magmortar',
       'Togekiss', 'Yanmega', 'Leafeon', 'Glaceon', 'Gliscor',
       'Mamoswine', 'Porygon-Z', 'Gallade', 'GalladeMega Gallade',
       'Probopass', 'Dusknoir', 'Froslass', 'Rotom', 'RotomHeat Rotom',
       'RotomWash Rotom', 'RotomFrost Rotom', 'RotomFan Rotom',
       'RotomMow Rotom', 'Uxie', 'Mesprit', 'Azelf', 'Dialga', 'Palkia',
       'Heatran', 'Regigigas', 'GiratinaAltered Forme',
       'GiratinaOrigin Forme', 'Cresselia', 'Phione', 'Manaphy',
       'Darkrai', 'ShayminLand Forme', 'ShayminSky Forme', 'Arceus',
       'Victini', 'Snivy', 'Servine', 'Serperior', 'Tepig', 'Pignite',
       'Emboar', 'Oshawott', 'Dewott', 'Samurott', 'Patrat', 'Watchog',
       'Lillipup', 'Herdier', 'Stoutland', 'Purrloin', 'Liepard',
       'Pansage', 'Simisage', 'Pansear', 'Simisear', 'Panpour',
       'Simipour', 'Munna', 'Musharna', 'Pidove', 'Tranquill', 'Unfezant',
       'Blitzle', 'Zebstrika', 'Roggenrola', 'Boldore', 'Gigalith',
       'Woobat', 'Swoobat', 'Drilbur', 'Excadrill', 'Audino',
       'AudinoMega Audino', 'Timburr', 'Gurdurr', 'Conkeldurr', 'Tympole',
       'Palpitoad', 'Seismitoad', 'Throh', 'Sawk', 'Sewaddle', 'Swadloon',
       'Leavanny', 'Venipede', 'Whirlipede', 'Scolipede', 'Cottonee',
       'Whimsicott', 'Petilil', 'Lilligant', 'Basculin', 'Sandile',
       'Krokorok', 'Krookodile', 'Darumaka', 'DarmanitanStandard Mode',
       'DarmanitanZen Mode', 'Maractus', 'Dwebble', 'Crustle', 'Scraggy',
       'Scrafty', 'Sigilyph', 'Yamask', 'Cofagrigus', 'Tirtouga',
       'Carracosta', 'Archen', 'Archeops', 'Trubbish', 'Garbodor',
       'Zorua', 'Zoroark', 'Minccino', 'Cinccino', 'Gothita', 'Gothorita',
       'Gothitelle', 'Solosis', 'Duosion', 'Reuniclus', 'Ducklett',
       'Swanna', 'Vanillite', 'Vanillish', 'Vanilluxe', 'Deerling',
       'Sawsbuck', 'Emolga', 'Karrablast', 'Escavalier', 'Foongus',
       'Amoonguss', 'Frillish', 'Jellicent', 'Alomomola', 'Joltik',
       'Galvantula', 'Ferroseed', 'Ferrothorn', 'Klink', 'Klang',
       'Klinklang', 'Tynamo', 'Eelektrik', 'Eelektross', 'Elgyem',
       'Beheeyem', 'Litwick', 'Lampent', 'Chandelure', 'Axew', 'Fraxure',
       'Haxorus', 'Cubchoo', 'Beartic', 'Cryogonal', 'Shelmet',
       'Accelgor', 'Stunfisk', 'Mienfoo', 'Mienshao', 'Druddigon',
       'Golett', 'Golurk', 'Pawniard', 'Bisharp', 'Bouffalant', 'Rufflet',
       'Braviary', 'Vullaby', 'Mandibuzz', 'Heatmor', 'Durant', 'Deino',
       'Zweilous', 'Hydreigon', 'Larvesta', 'Volcarona', 'Cobalion',
       'Terrakion', 'Virizion', 'TornadusIncarnate Forme',
       'TornadusTherian Forme', 'ThundurusIncarnate Forme',
       'ThundurusTherian Forme', 'Reshiram', 'Zekrom',
       'LandorusIncarnate Forme', 'LandorusTherian Forme', 'Kyurem',
       'KyuremBlack Kyurem', 'KyuremWhite Kyurem', 'KeldeoOrdinary Forme',
       'KeldeoResolute Forme', 'MeloettaAria Forme',
       'MeloettaPirouette Forme', 'Genesect', 'Chespin', 'Quilladin',
       'Chesnaught', 'Fennekin', 'Braixen', 'Delphox', 'Froakie',
       'Frogadier', 'Greninja', 'Bunnelby', 'Diggersby', 'Fletchling',
       'Fletchinder', 'Talonflame', 'Scatterbug', 'Spewpa', 'Vivillon',
       'Litleo', 'Pyroar', 'FlabÃ©bÃ©', 'Floette', 'Florges', 'Skiddo',
       'Gogoat', 'Pancham', 'Pangoro', 'Furfrou', 'Espurr',
       'MeowsticMale', 'MeowsticFemale', 'Honedge', 'Doublade',
       'AegislashBlade Forme', 'AegislashShield Forme', 'Spritzee',
       'Aromatisse', 'Swirlix', 'Slurpuff', 'Inkay', 'Malamar', 'Binacle',
       'Barbaracle', 'Skrelp', 'Dragalge', 'Clauncher', 'Clawitzer',
       'Helioptile', 'Heliolisk', 'Tyrunt', 'Tyrantrum', 'Amaura',
       'Aurorus', 'Sylveon', 'Hawlucha', 'Dedenne', 'Carbink', 'Goomy',
       'Sliggoo', 'Goodra', 'Klefki', 'Phantump', 'Trevenant',
       'PumpkabooAverage Size', 'PumpkabooSmall Size',
       'PumpkabooLarge Size', 'PumpkabooSuper Size',
       'GourgeistAverage Size', 'GourgeistSmall Size',
       'GourgeistLarge Size', 'GourgeistSuper Size', 'Bergmite',
       'Avalugg', 'Noibat', 'Noivern', 'Xerneas', 'Yveltal',
       'Zygarde50% Forme', 'Diancie', 'DiancieMega Diancie',
       'HoopaHoopa Confined', 'HoopaHoopa Unbound', 'Volcanion'],
      dtype=object)

#### Create a new column called `A/D Ratio` whose value equals to `Attack` devided by `Defense`.

For instance, if a pokemon has the Attack score 49 and Defense score 49, the corresponding `A/D Ratio` is 49/49=1.

In [13]:

pokemon["A/D Ratio"] = pokemon["Attack"]/pokemon["Defense"]

new_pokemon = pokemon[["Name","Type 1","Type 2", "Total", "HP", "Attack", "Defense", "Sp. Atk", "Sp. Def", "Speed", "Generation", "Legendary", "A/D Ratio"]]
new_pokemon

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio
0,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,1.000000
1,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,0.984127
2,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,0.987952
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,0.813008
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,1.209302
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,0.666667
796,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,1.454545
797,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,1.833333
798,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,2.666667
799,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,0.916667

#### Identify the pokemon with the highest `A/D Ratio`.

In [14]:

new_pokemon.groupby(["Name"])['A/D Ratio'].max()

Name
Abomasnow                  1.226667
AbomasnowMega Abomasnow    1.257143
Abra                       1.333333
Absol                      2.166667
AbsolMega Absol            2.500000
                             ...
Zoroark                    1.750000
Zorua                      1.625000
Zubat                      1.285714
Zweilous                   1.214286
Zygarde50% Forme           0.826446
Name: A/D Ratio, Length: 800, dtype: float64

#### Identify the pokemon with the lowest A/D Ratio.

In [15]:

new_pokemon.groupby(["Name"])['A/D Ratio'].min()

Name
Abomasnow                  1.226667
AbomasnowMega Abomasnow    1.257143
Abra                       1.333333
Absol                      2.166667
AbsolMega Absol            2.500000
                             ...
Zoroark                    1.750000
Zorua                      1.625000
Zubat                      1.285714
Zweilous                   1.214286
Zygarde50% Forme           0.826446
Name: A/D Ratio, Length: 800, dtype: float64

#### Create a new column called `Combo Type` whose value combines `Type 1` and `Type 2`.

Rules:

* If both `Type 1` and `Type 2` have valid values, the `Combo Type` value should contain both values in the form of `<Type 1> <Type 2>`. For example, if `Type 1` value is `Grass` and `Type 2` value is `Poison`, `Combo Type` will be `Grass-Poison`.

* If `Type 1` has valid value but `Type 2` is not, `Combo Type` will be the same as `Type 1`. For example, if `Type 1` is `Fire` whereas `Type 2` is `NaN`, `Combo Type` will be `Fire`.

In [28]:

#pokemon["Combo Type"] = pokemon["Type 1"] + pokemon["Type 2"]

#new_pokemon_2 = pokemon[["Name","Type 1","Type 2", "Total", "HP", "Attack", "Defense", "Sp. Atk", "Sp. Def", "Speed", "Generation", "Legendary", "A/D Ratio", "Combo Type"]]
#new_pokemon_2

new_pokemon ["Combo Type"] = pokemon["Type 1"] + pokemon["Type 2"]
new_pokemon_2 = new_pokemon[["Name","Type 1","Type 2", "Total", "HP", "Attack", "Defense", "Sp. Atk", "Sp. Def", "Speed", "Generation", "Legendary", "A/D Ratio", "Combo Type"]]
new_pokemon_2

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio,Combo Type
0,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,1.000000,GrassPoison
1,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,0.984127,GrassPoison
2,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,0.987952,GrassPoison
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,0.813008,GrassPoison
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,1.209302,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,0.666667,RockFairy
796,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,1.454545,RockFairy
797,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,1.833333,PsychicGhost
798,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,2.666667,PsychicDark
799,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,0.916667,FireWater

#### Identify the pokemon whose `A/D Ratio` are among the top 5.

In [37]:


new_pokemon_3 = new_pokemon_2.sort_values(['A/D Ratio'], ascending=[0])

new_pokemon_3.head(5)

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio,Combo Type
429,DeoxysAttack Forme,Psychic,NaN,600,50,180,20,180,20,150,3,True,9.000,NaN
347,Carvanha,Water,Dark,305,45,90,20,65,20,65,3,False,4.500,WaterDark
19,BeedrillMega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False,3.750,BugPoison
453,Cranidos,Rock,NaN,350,67,125,40,30,30,58,4,False,3.125,NaN
348,Sharpedo,Water,Dark,460,70,120,40,95,40,95,3,False,3.000,WaterDark

#### For the 5 pokemon printed above, aggregate `Combo Type` and use a list to store the unique values.

Your end product is a list containing the distinct `Combo Type` values of the 5 pokemon with the highest `A/D Ratio`.

In [40]:
new_pokemon_4= new_pokemon_3["Combo Type"].unique()
new_pokemon_4

array([nan, 'WaterDark', 'BugPoison', 'SteelGhost', 'PsychicDark',
       'RockFlying', 'DarkFlying', 'GroundSteel', 'NormalFairy',
       'GrassPoison', 'GroundDark', 'FireFighting', 'BugGhost',
       'BugFlying', 'IcePsychic', 'NormalFlying', 'DarkFire',
       'PsychicFighting', 'GrassDark', 'RockBug', 'DarkIce',
       'PsychicGhost', 'GhostFlying', 'DragonFlying', 'DragonIce',
       'BugFighting', 'FightingSteel', 'ElectricFlying', 'PoisonFighting',
       'GrassFighting', 'IceGround', 'GroundFlying', 'FightingDark',
       'WaterFlying', 'DragonGround', 'GroundGhost', 'BugFire',
       'FireGround', 'GrassDragon', 'GhostGrass', 'RockFairy',
       'NormalFighting', 'FireFlying', 'RockFighting', 'NormalGrass',
       'NormalWater', 'GroundDragon', 'PoisonDark', 'GrassFlying',
       'WaterGround', 'PoisonGround', 'PsychicFairy', 'BugSteel',
       'DarkDragon', 'DragonPsychic', 'BugGrass', 'PoisonFlying',
       'BugElectric', 'RockGround', 'WaterPoison', 'GrassIce',
       'DragonElectric', 'DarkSteel', 'NormalPsychic', 'FightingFlying',
       'IceFlying', 'RockDark', 'WaterDragon', 'GhostDragon',
       'DragonFire', 'RockIce', 'FightingPsychic', 'FireDragon',
       'GhostPoison', 'RockDragon', 'ElectricNormal', 'IceGhost',
       'GroundFire', 'GrassPsychic', 'RockPsychic', 'PsychicFlying',
       'RockWater', 'GroundRock', 'DarkFighting', 'WaterIce',
       'DarkPsychic', 'SteelPsychic', 'GrassGround', 'ElectricFairy',
       'WaterGrass', 'SteelDragon', 'WaterElectric', 'PsychicFire',
       'PsychicGrass', 'PoisonWater', 'WaterPsychic', 'DragonFairy',
       'SteelFairy', 'DarkGhost', 'WaterFighting', 'WaterSteel',
       'FirePsychic', 'FireNormal', 'BugWater', 'FireWater',
       'ElectricDragon', 'IceWater', 'FlyingDragon', 'WaterGhost',
       'GhostDark', 'FireSteel', 'RockGrass', 'PoisonDragon', 'WaterRock',
       'GrassFairy', 'GroundElectric', 'BugRock', 'BugGround',
       'NormalGround', 'GroundPsychic', 'GrassSteel', 'SteelRock',
       'SteelFighting', 'GhostFire', 'ElectricGhost', 'ElectricSteel',
       'WaterFairy', 'ElectricGrass', 'ElectricFire', 'ElectricWater',
       'ElectricIce', 'SteelFlying', 'PoisonBug', 'SteelGround',
       'FairyFlying', 'FireRock', 'RockSteel'], dtype=object)

#### For each of the `Combo Type` values obtained from the previous question, calculate the mean scores of all numeric fields across all pokemon.

Your output should look like below:

![Aggregate](../images/aggregated-mean.png)

In [19]:
# your code here